/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./components/Body.vue')['default']
    FilterPanel: typeof import('./components/FilterPanel.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameDetail: typeof import('./components/GameDetail.vue')['default']
    GameForm: typeof import('./components/GameForm.vue')['default']
    GameGrid: typeof import('./components/GameGrid.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    StarRating: typeof import('./components/StarRating.vue')['default']
  }
}
